### ISSUE TITLE
Bad address

### ISSUE THREAD

**Issue by hotice** [rasguanabana/ytfs#23]
Trying to open a file, copy it, etc., the "bad address" error is displayed. Using ytfs installed using "pip3 install ytfs" in Ubuntu 16.04 (64bit).

Running ytfs in debug mode displays the following error:

```
$ ytfs -d youtube
Mounting YTFS ver. 0.99a4.
If you encounter any bugs, please open an issue on GitHub: https://github.com/rasguanabana/ytfs
Traceback (most recent call last):
  File "/home/andrei/.local/lib/python3.5/site-packages/fuse.py", line 495, in _wrapper
    return func(*args, **kwargs) or 0
  File "/home/andrei/.local/lib/python3.5/site-packages/fuse.py", line 572, in open
    fi.flags)
  File "/home/andrei/.local/lib/python3.5/site-packages/fuse.py", line 800, in __call__
    return getattr(self, op)(*args)
  File "/home/andrei/.local/lib/python3.5/site-packages/ytfs/ytfs.py", line 323, in mod
    return method(self, self.__pathToTuple(path), *args)
  File "/home/andrei/.local/lib/python3.5/site-packages/ytfs/ytfs.py", line 565, in open
    if yts.obtainInfo(): #FIXME coz it's ugly.
  File "/home/andrei/.local/lib/python3.5/site-packages/ytfs/stor.py", line 234, in obtainInfo
    if self.preferences['audio'] and self.preferences['video']: fm = sorted(full, key=_k)
TypeError: unorderable types: str() < int()

```

**Comment by rasguanabana** [comment]
Could you please check with latest repo version? I haven't updated PyPI package in quite some time. I will do that, if it works correctly (should be fixed by 81f7b33 and later)

**Comment by hotice** [comment]
Now that error doesn't occur but it still doesn't work. For instance, I copied 2 videos and they one was about 4kb, the other 11 mb, and both couldn't be played by either vlc or mpv. I tried playing them directly to get some debug, but nothing showed up using `ytfs -d`.

**Comment by rasguanabana** [comment]
Probably caching is very buggy. I will investigate on it next week.
